// QUẢN LÝ NGÔN NGỮ (EN / VI)
// ==========================================
const translations = {
  EN: {
    nav_home: "Home",
    nav_rescue: "Rescue Map",
    nav_social: "Social",
    nav_species: "Species Library",
    nav_game: "Game",
    nav_contact: "Contact Us",
    chatbot_greeting: "Hello! I'm Phoenix 🦅 Your wildlife guardian assistant! How can I help you today?",
    qr_1: " How can I report an emergency?",
    qr_2: " I want to interact with the community!",
    qr_3: " I want to play and learn!",
    qr_4: " Where to lookup species info?",
    btn_report: "🚨 Report Now",
    btn_login: "→ Log in",
    post_placeholder: "Share something with the community...",
    btn_photo: " Photo",
    cat_story: "Story",
    cat_adoption: "Adoption",
    cat_donations: "Donations",
    cat_orgs: "Organizations",
    btn_post: "Post",
    filter_all: "All Posts",
    filter_adoption: "Adoption",
    filter_donations: "Donations",
    filter_orgs: "Organizations",
    filter_stories: "Stories",
    title_friends: "Friends",
    search_friends_placeholder: "Enter a name to find friends...",
    title_requests: "Requests",
    no_invitations: "No invitations",
    title_messages: "Messages",
    search_messages_placeholder: "Search friends...",
    btn_message: "Message",
    btn_add_friend: "Add friend",
    btn_settings: " Settings",
    btn_logout: " Log out",
    del_post_title: "Delete post?",
    del_post_desc: "Are you sure you want to delete this post?",
    btn_delete: "Delete",
    btn_cancel: "Cancel",
    del_comment_title: "Delete comment?",
    del_comment_desc: "Are you sure you want to delete this comment?",
    edit_post_title: "Edit post",
    btn_change_media: " Change media",
    btn_save_changes: "Save changes",
    update_profile_title: "Update profile",
    update_profile_desc: "Choose an avatar and display name to get started!",
    name_placeholder: "Your display name...",
    btn_save_profile: "Save Profile",
    btn_skip: "Skip (Anonymous)",
    view_replies: "View replies",
    hide_replies: "Hide replies",
    anonymous_user: "Anonymous user",
    write_comment: "Write a comment...",
    attach_image: " Attach image",
    btn_send: "Send",
    saving: "Saving...",
    cancel_request: "Cancel request",
    no_friend_requests: "No friend requests",
    click_to_message: "Click to message...",
    please_enter_name: "Please enter a name!",
    error_try_again: "Error! Please try again",
    network_error: "Network error! Try again",
    processing: "Processing...",
    search_to_start: "Let's search to start a conversation!",
    like: "Like",
    likes: "Likes",
    reply: "Reply",
    tooltip_edit_post: "Edit post",
    tooltip_delete_post: "Delete post",
    tooltip_delete_comment: "Delete comment",
    profile_settings_title: "Profile settings",
    profile_settings_desc: "Change your name and avatar.",
    lib_chip: "📚 Holographic Database",
    lib_title_1: "Species",
    lib_title_2: "Library of Vietnam",
    lib_desc: "Discover our world's magnificent creatures. Play the rescue game to unlock exclusive 3D holographic views and comprehensive data!",
    lib_stat_species: "Species",
    lib_stat_redbook: "Vietnam Red Data Book",
    lib_stat_play: "Play to unlock 3D",
    lib_search_placeholder: "Search species by name...",
    lib_cat_all: "All Categories",
    lib_cat_mammals: "Mammals",
    lib_cat_birds: "Birds",
    lib_cat_reptiles: "Reptiles",
    lib_cat_amphibians: "Amphibians",
    lib_cat_fish: "Fish",
    lib_cat_insects: "Insects",
    hero_badge: "Join the Movement",
    hero_title: "Protect Wildlife, Together.",
    hero_desc: "Be part of a global community dedicated to rescuing, protecting, and preserving wildlife. Report emergencies, connect with rescuers, and learn about the amazing creatures we share our planet with.",
    hero_btn_report: "Report Emergency",
    hero_btn_explore: "Explore Species",
    stat_guardians: "Guardians",
    stat_rescued: "Rescued",
    stat_communities: "Communities",
    badge_rescues: "Rescues this month",
    badge_vets: "Vets online",
    contact_badge: "We'd love to hear from you",
    contact_title: "Get in Touch, Let's Protect Wildlife Together.",
    contact_desc: "Have a question, spotted an animal in distress, or want to join our mission? Our team is ready to connect with you. Every conversation matters.",
    contact_btn: "Send a Message",
    contact_team_btn: "Meet the Team",
    impact_title: "Our Impact in Numbers",
    impact_guardians: "Active Guardians",
    impact_rescued: "Animals Rescued",
    impact_communities: "Communities",
    impact_species: "Species Documented",
    help_chip: "🌿 Get Involved",
    help_title: "How You Can Help",
    help_desc: "Every action counts. From reporting an injured animal to joining a community, there are many ways to contribute to wildlife conservation.",
    help_map_title: "Rescue Map",
    help_map_desc: "Report and track injured animals in real-time with our interactive emergency map.",
    learn_more: "Learn more",
    help_community_title: "Community",
    help_community_desc: "Connect with fellow wildlife enthusiasts, share stories, and organize rescue efforts.",
    help_library_title: "Species Library",
    help_library_desc: "Explore our comprehensive encyclopedia of wildlife species with AI-powered identification.",
    help_network_title: "Protection Network",
    help_network_desc: "Join verified volunteer networks and local animal rescue organizations near you.",
    comm_chip: "👥 Network",
    comm_title: "Active Communities",
    comm_desc: "Join like-minded wildlife enthusiasts in your area",
    comm_c1_title: "Coastal Wildlife Protectors",
    comm_c1_desc: "Protecting shorelines from human impact through collective conservation.",
    comm_c1_tag: "Coastal",
    comm_c2_title: "Bird Sanctuary Alliance",
    comm_c2_desc: "A global alliance of birders and conservationists preserving avian habitats.",
    comm_c2_tag: "Avian",
    comm_c3_title: "Forest Friends Network",
    comm_c3_desc: "Safeguarding ancient forests and the wildlife that call them home.",
    comm_c3_tag: "Forest",
    comm_c4_title: "Marine Life Guardians",
    comm_c4_desc: "Dedicated to protecting ocean ecosystems and marine biodiversity worldwide.",
    comm_c4_tag: "Marine",
    comm_c5_title: "Urban Wildlife Watch",
    comm_c5_desc: "Monitoring and protecting wildlife in and around urban environments.",
    comm_c5_tag: "Urban",
    comm_c6_title: "Reptile Rescue Rangers",
    comm_c6_desc: "Specialized rescue teams focused on reptile conservation and welfare.",
    comm_c6_tag: "Reptile",
    btn_join: "Join",
    btn_view_all_comm: "View All Communities",
    news_chip: "📰 Latest",
    news_title: "Wildlife News",
    news_desc: "Stay updated with the latest conservation news and discoveries",
    news_f_tag: "Discovery",
    news_f_time: "2 hours ago",
    news_f_title: "Rare White Tiger Spotted in National Park",
    news_f_desc: "Wildlife researchers are excited after a rare white tiger was photographed in the wild for the first time in decades.",
    news_f_read: "Read full story →",
    news_1_tag: "Rescue",
    news_1_time: "1 day ago",
    news_1_title: "Community Effort Saves 200 Stranded Dolphins",
    news_1_desc: "Local volunteers and Wildlife Guardian members work together in a successful rescue operation along the coast.",
    news_2_tag: "Technology",
    news_2_time: "5 hours ago",
    news_2_title: "AI Technology Helps Track Endangered Species",
    news_2_desc: "New machine learning models are revolutionizing how conservationists monitor wildlife populations globally.",
    news_3_tag: "Policy",
    news_3_time: "2 days ago",
    news_3_title: "New Marine Protection Zone Established",
    news_3_desc: "Government announces a 500km protected marine area to safeguard endangered sea turtle populations worldwide.",
    news_read_more: "Read more →",
    btn_view_all_news: "View All News",
    cta_badge: "🌍 Join the Movement",
    cta_title: "Ready to Make a Difference?",
    cta_desc: "Join thousands of wildlife guardians protecting our planet's most precious creatures. Every report, every share, every action counts.",
    cta_btn_start: "Get Started Free",
    cta_btn_contact: "Contact Us",
    cta_trust_1: "✓ Free to join",
    cta_trust_2: "✓ No credit card required",
    cta_trust_3: "✓ Instant access",
    ft_desc: "Protecting wildlife together, one rescue at a time.",
    ft_platform: "Platform",
    ft_support: "Support",
    ft_legal: "Legal",
    ft_rights: "© 2026 Wildlife Guardian. All rights reserved.",
    ct_pill_1: "Support team online now",
    ct_pill_2: "Reply within 24 hours",
    ct_pill_3: "Available in 12 languages",
    team_chip: "👥 Our People",
    team_title: "Meet The Team",
    team_desc: "Passionate individuals united by one mission — protecting the wildlife that shares our planet.",
    team_role_1: "Lead Developer & Project Manager",
    team_bio_1: "Architecting the Wildlife Guardian platform and leading the mission from vision to reality.",
    team_role_2: "UI/UX Designer & Frontend Dev",
    team_bio_2: "Crafting beautiful, intuitive experiences that make conservation feel inspiring and accessible.",
    team_role_3: "Backend Engineer & Data Analyst",
    team_bio_3: "Building robust systems to power real-time rescue operations and wildlife tracking across the globe.",
    team_role_4: "Conservation Researcher",
    team_bio_4: "Conducting field research to document endangered species and inform our platform's conservation strategies.",
    ci_chip: "✉️ Reach Out",
    ci_title: "Contact Information & Form",
    ci_desc: "Fill in the form or reach us directly through any of the channels below.",
    ci_channels: "Direct Channels",
    ci_email: "Email Address",
    ci_hotline: "Support Hotline",
    ci_hq: "Headquarters",
    ci_hours: "Office Hours",
    ci_hours_val: "Mon – Fri: 8:00 AM – 6:00 PM (ICT, UTC+7)",
    ci_follow: "Follow Our Mission",
    form_title: "Send a Message",
    form_name: "Your Name",
    form_name_ph: "John Doe",
    form_email: "Email Address",
    form_subject: "Subject",
    form_subject_ph: "How can we help you?",
    form_msg: "Your Message",
    form_msg_ph: "Tell us about an animal in distress, share your ideas, or just say hello…",
    form_send: "Send Message",
    form_succ_title: "Message sent!",
    form_succ_desc: "Thank you for reaching out. We'll get back to you within 24 hours.",
    donate_badge: "❤️ Support the Mission",
    donate_title: "Every Donation Saves Lives",
    donate_desc: "Your contribution directly funds rescue operations, habitat restoration, and the technology that connects guardians worldwide. No amount is too small — every rupee, dong, dollar counts.",
    donate_10: "Feeds a rescued animal for a week",
    donate_50: "Funds a field survey day",
    donate_200: "Sponsors a rescue operation",
    donate_btn: "Donate Now",
    donate_learn: "Learn How It's Used",
    donate_trust: "🔒 Secure payments · 100% goes to conservation · Tax-deductible in most countries",
    btn_settings: "Settings",
    btn_logout: "Log out",
    update_profile_title: "Update profile",
    update_profile_desc: "Choose an avatar and display name to get started!",
    name_placeholder: "Your display name...",
    btn_save_profile: "Save Profile",
    btn_skip: "Skip (Anonymous)",
    sp_habitat: "Habitat",
    sp_foundin: "Found In",
    sp_diet: "Diet",
    sp_behavior: "Behavior",
    sp_funfact: "Fun Fact",
    rm_search_ph: "Search animal, location...",
    rm_tab_all: "All",
    rm_tab_emergency: "Emergency",
    rm_tab_progress: "In Progress",
    rm_tab_rescued: "Rescued",
    rm_leg_emergency: "Emergency",
    rm_leg_progress: "In Progress",
    rm_leg_rescued: "Rescued",
    rm_fa_title: "Quick First Aid Guide",
    rm_fa_1_title: "1. Keep a safe distance",
    rm_fa_1_desc: "Do not rush to approach. Frightened wild animals may attack. Observe from a distance.",
    rm_fa_2_title: "2. Prepare a dark box",
    rm_fa_2_desc: "Use a cardboard box with air holes. Line with soft cloth inside to create a dark and quiet space.",
    rm_fa_3_title: "3. DO NOT feed them",
    rm_fa_3_desc: "Incorrect feeding or forcing water can cause the animal to choke or die instantly.",
    rm_fa_4_title: "4. Call experts",
    rm_fa_4_desc1: "Immediately contact hotline ",
    rm_fa_4_desc2: " or nearest rescue station for assistance.",
    rm_btn_env: "Learn more at ENV",
    rm_modal_title: "Report Animal in Need of Rescue",
    rm_scan_label: "Point camera at the animal",
    rm_btn_capture: " Capture",
    rm_btn_retake: " Retake",
    rm_reporter_label: "Reporter",
    rm_reporter_guest: "Guest",
    rm_lbl_animal: "Animal Name/Species *",
    rm_lbl_status: "Status *",
    rm_opt_emergency: "🚨 Emergency – Needs immediate help",
    rm_opt_progress: "⏳ In Progress – Help is on the way",
    rm_opt_rescued: "✅ Rescued – Safe",
    rm_lbl_phone: "Contact Phone *",
    rm_lbl_desc: "Additional Details (Optional)",
    rm_loc_loading: "Determining GPS location...",
    rm_loc_fetching: "Fetching address...",
    rm_btn_submit: "Submit Rescue Report",
    rm_card_reporter: "Reporter: ",
    rm_card_phone: "Phone: ",
    rm_card_status: "Status: ",
    rm_card_desc: "Desc: ",
    rm_card_time: "Time: ",
    rm_card_btn_guide: "First Aid Guide",
    rm_card_btn_call: "Call Expert",
    rm_status_text_emergency: "EMERGENCY",
    rm_status_text_progress: "IN PROGRESS",
    rm_status_text_rescued: "RESCUED"
  },
  VI: {
    nav_home: "Trang chủ",
    nav_rescue: "Bản đồ cứu hộ",
    nav_social: "Cộng đồng",
    nav_species: "Thư viện loài",
    nav_game: "Trò chơi",
    nav_contact: "Liên hệ",
    chatbot_greeting: "Chào bạn! Tôi là Phoenix 🦅 Trợ lý bảo vệ động vật hoang dã của bạn! Tôi có thể giúp gì cho bạn hôm nay?",
    qr_1: " Làm sao để báo cáo khẩn cấp?",
    qr_2: " Tôi muốn giao lưu với cộng đồng!",
    qr_3: " Tôi muốn vừa học vừa chơi!",
    qr_4: " Nơi tra cứu thông tin các loài?",
    btn_report: "🚨 Báo cáo",
    btn_login: "→ Đăng nhập",
    post_placeholder: "Chia sẻ điều gì đó với cộng đồng...",
    btn_photo: " Ảnh",
    cat_story: "Câu chuyện",
    cat_adoption: "Nhận nuôi",
    cat_donations: "Quyên góp",
    cat_orgs: "Tổ chức",
    btn_post: "Đăng",
    filter_all: "Tất cả",
    filter_adoption: "Nhận nuôi",
    filter_donations: "Quyên góp",
    filter_orgs: "Tổ chức",
    filter_stories: "Câu chuyện",
    title_friends: "Bạn bè",
    search_friends_placeholder: "Nhập tên để tìm bạn...",
    title_requests: "Lời mời",
    no_invitations: "Không có lời mời",
    title_messages: "Tin nhắn",
    search_messages_placeholder: "Tìm kiếm bạn bè...",
    btn_message: "Nhắn tin",
    btn_add_friend: "Thêm bạn bè",
    btn_settings: " Cài đặt",
    btn_logout: " Đăng xuất",
    del_post_title: "Xóa bài viết?",
    del_post_desc: "Bạn có chắc chắn muốn xóa bài viết này không?",
    btn_delete: "Xóa",
    btn_cancel: "Hủy",
    del_comment_title: "Xóa bình luận?",
    del_comment_desc: "Bạn có chắc chắn muốn xóa bình luận này không?",
    edit_post_title: "Chỉnh sửa bài viết",
    btn_change_media: " Đổi ảnh/video",
    btn_save_changes: "Lưu thay đổi",
    update_profile_title: "Cập nhật hồ sơ",
    update_profile_desc:
      "Hãy chọn ảnh đại diện và tên hiển thị để bắt đầu nhé!",
    name_placeholder: "Tên hiển thị của bạn...",
    btn_save_profile: "Lưu hồ sơ",
    btn_skip: "Để sau (Ẩn danh)",
    view_replies: "Xem câu trả lời",
    hide_replies: "Ẩn câu trả lời",
    anonymous_user: "Người dùng ẩn danh",
    write_comment: "Viết bình luận...",
    attach_image: " Đính kèm ảnh",
    btn_send: "Gửi",
    saving: "Đang lưu...",
    cancel_request: "Hủy lời mời",
    no_friend_requests: "Chưa có lời mời",
    click_to_message: "Bấm để nhắn tin...",
    please_enter_name: "Vui lòng nhập tên!",
    error_try_again: "Lỗi! Vui lòng thử lại",
    network_error: "Lỗi mạng! Thử lại",
    processing: "Đang xử lý...",
    search_to_start: "Hãy tìm kiếm để bắt đầu cuộc trò chuyện!",
    like: "Thích",
    likes: "Thích",
    reply: "Trả lời",
    tooltip_edit_post: "Sửa bài viết",
    tooltip_delete_post: "Xóa bài viết",
    tooltip_delete_comment: "Xóa bình luận",
    profile_settings_title: "Cài đặt hồ sơ",
    profile_settings_desc: "Thay đổi tên và ảnh đại diện của bạn.",
    lib_chip: "📚 Cơ Sở Dữ Liệu Hologram",
    lib_title_1: "Thư Viện Động Vật",
    lib_title_2: "Việt Nam",
    lib_desc: "Khám phá những sinh vật tuyệt vời trên thế giới. Hãy chơi game giải cứu để mở khóa chế độ xem 3D Hologram độc quyền và kho dữ liệu chi tiết!",
    lib_stat_species: "Loài",
    lib_stat_redbook: "Sách Đỏ Việt Nam",
    lib_stat_play: "Chơi game để mở khóa 3D",
    lib_search_placeholder: "Tìm kiếm loài theo tên...",
    lib_cat_all: "Tất cả",
    lib_cat_mammals: "Thú (Động vật có vú)",
    lib_cat_birds: "Chim",
    lib_cat_reptiles: "Bò sát",
    lib_cat_amphibians: "Lưỡng cư",
    lib_cat_fish: "Cá",
    lib_cat_insects: "Côn trùng",
    hero_badge: "Tham Gia Ngay",
    hero_title: "Bảo Vệ Động Vật, Cùng Nhau.",
    hero_desc: "Hãy trở thành một phần của cộng đồng toàn cầu cống hiến cho việc giải cứu, bảo vệ và bảo tồn động vật hoang dã. Báo cáo khẩn cấp, kết nối với đội cứu hộ và tìm hiểu về những sinh vật tuyệt vời trên hành tinh của chúng ta.",
    hero_btn_report: "Báo cáo Khẩn Cấp",
    hero_btn_explore: "Khám Phá Thư Viện",
    stat_guardians: "Người Bảo Vệ",
    stat_rescued: "Đã Cứu",
    stat_communities: "Cộng Đồng",
    badge_rescues: "Ca cứu hộ tháng này",
    badge_vets: "Bác sĩ thú y trực tuyến",
    contact_badge: "Chúng tôi luôn lắng nghe bạn",
    contact_title: "Hãy Liên Hệ, Cùng Nhau Bảo Vệ Động Vật Hoang Dã.",
    contact_desc: "Có thắc mắc, phát hiện động vật bị thương, hay muốn tham gia sứ mệnh của chúng tôi? Đội ngũ của chúng tôi sẵn sàng kết nối với bạn. Mọi cuộc trò chuyện đều quan trọng.",
    contact_btn: "Gửi Tin Nhắn",
    contact_team_btn: "Gặp Gỡ Đội Ngũ",
    impact_title: "Tác Động Của Chúng Tôi",
    impact_guardians: "Người Bảo Vệ Tích Cực",
    impact_rescued: "Động Vật Được Cứu",
    impact_communities: "Cộng Đồng",
    impact_species: "Loài Được Ghi Chép",
    help_chip: "🌿 Tham Gia Ngay",
    help_title: "Cách Bạn Có Thể Giúp Đỡ",
    help_desc: "Mỗi hành động đều có ý nghĩa. Từ việc báo cáo động vật bị thương đến tham gia cộng đồng, có rất nhiều cách để đóng góp vào bảo tồn động vật hoang dã.",
    help_map_title: "Bản Đồ Cứu Hộ",
    help_map_desc: "Báo cáo và theo dõi động vật bị thương theo thời gian thực với bản đồ khẩn cấp tương tác của chúng tôi.",
    learn_more: "Tìm hiểu thêm",
    help_community_title: "Cộng Đồng",
    help_community_desc: "Kết nối với những người đam mê động vật hoang dã, chia sẻ câu chuyện và tổ chức các nỗ lực cứu hộ.",
    help_library_title: "Thư Viện Loài",
    help_library_desc: "Khám phá bách khoa toàn thư toàn diện về các loài động vật hoang dã với tính năng nhận dạng bằng AI.",
    help_network_title: "Mạng Lưới Bảo Vệ",
    help_network_desc: "Tham gia các mạng lưới tình nguyện viên được xác minh và các tổ chức cứu hộ động vật địa phương gần bạn.",
    comm_chip: "👥 Mạng Lưới",
    comm_title: "Cộng Đồng Tích Cực",
    comm_desc: "Tham gia cùng những người đam mê động vật hoang dã trong khu vực của bạn",
    comm_c1_title: "Bảo vệ Động vật hoang dã Ven biển",
    comm_c1_desc: "Bảo vệ bờ biển khỏi tác động của con người thông qua bảo tồn tập thể.",
    comm_c1_tag: "Ven biển",
    comm_c2_title: "Liên minh Khu bảo tồn Chim",
    comm_c2_desc: "Một liên minh toàn cầu của những người xem chim và nhà bảo tồn gìn giữ môi trường sống của chim.",
    comm_c2_tag: "Chim chóc",
    comm_c3_title: "Mạng lưới Bạn bè của Rừng",
    comm_c3_desc: "Bảo vệ những khu rừng cổ thụ và động vật hoang dã coi đó là nhà.",
    comm_c3_tag: "Rừng",
    comm_c4_title: "Người bảo vệ Sinh vật Biển",
    comm_c4_desc: "Tận tâm bảo vệ hệ sinh thái đại dương và đa dạng sinh học biển trên toàn thế giới.",
    comm_c4_tag: "Biển",
    comm_c5_title: "Trạm gác Động vật hoang dã Đô thị",
    comm_c5_desc: "Theo dõi và bảo vệ động vật hoang dã trong và xung quanh môi trường đô thị.",
    comm_c5_tag: "Đô thị",
    comm_c6_title: "Biệt đội Cứu hộ Bò sát",
    comm_c6_desc: "Các đội cứu hộ chuyên trách tập trung vào bảo tồn và phúc lợi của các loài bò sát.",
    comm_c6_tag: "Bò sát",
    btn_join: "Tham gia",
    btn_view_all_comm: "Xem Tất Cả Cộng Đồng",
    news_chip: "📰 Mới Nhất",
    news_title: "Tin Tức Động Vật Hoang Dã",
    news_desc: "Cập nhật những tin tức và khám phá bảo tồn mới nhất",
    news_f_tag: "Khám phá",
    news_f_time: "2 giờ trước",
    news_f_title: "Phát hiện Hổ Trắng hiếm tại Vườn Quốc gia",
    news_f_desc: "Các nhà nghiên cứu động vật hoang dã đang rất hào hứng sau khi một con hổ trắng hiếm được chụp ảnh trong tự nhiên lần đầu tiên sau nhiều thập kỷ.",
    news_f_read: "Đọc toàn bộ câu chuyện →",
    news_1_tag: "Cứu hộ",
    news_1_time: "1 ngày trước",
    news_1_title: "Nỗ lực cộng đồng cứu sống 200 con cá heo mắc cạn",
    news_1_desc: "Các tình nguyện viên địa phương và thành viên Wildlife Guardian làm việc cùng nhau trong một chiến dịch cứu hộ thành công dọc theo bờ biển.",
    news_2_tag: "Công nghệ",
    news_2_time: "5 giờ trước",
    news_2_title: "Công nghệ AI Giúp Theo Dõi Các Loài Có Nguy Cơ Tuyệt Chủng",
    news_2_desc: "Các mô hình học máy mới đang cách mạng hóa cách các nhà bảo tồn giám sát quần thể động vật hoang dã trên toàn cầu.",
    news_3_tag: "Chính sách",
    news_3_time: "2 ngày trước",
    news_3_title: "Khu vực Bảo vệ Biển mới được Thành lập",
    news_3_desc: "Chính phủ công bố một khu vực biển được bảo vệ rộng 500km để bảo vệ các quần thể rùa biển đang có nguy cơ tuyệt chủng trên toàn thế giới.",
    news_read_more: "Đọc thêm →",
    btn_view_all_news: "Xem Tất Cả Tin Tức",
    cta_badge: "🌍 Tham Gia Phong Trào",
    cta_title: "Sẵn Sàng Tạo Ra Sự Khác Biệt?",
    cta_desc: "Tham gia cùng hàng ngàn người bảo vệ động vật hoang dã bảo vệ những sinh vật quý giá nhất của hành tinh chúng ta. Mỗi báo cáo, mỗi lượt chia sẻ, mỗi hành động đều có ý nghĩa.",
    cta_btn_start: "Bắt Đầu Miễn Phí",
    cta_btn_contact: "Liên Hệ Với Chúng Tôi",
    cta_trust_1: "✓ Tham gia miễn phí",
    cta_trust_2: "✓ Không yêu cầu thẻ tín dụng",
    cta_trust_3: "✓ Truy cập ngay lập tức",
    ft_desc: "Cùng nhau bảo vệ động vật hoang dã, từng cuộc cứu hộ một.",
    ft_platform: "Nền Tảng",
    ft_support: "Hỗ Trợ",
    ft_legal: "Pháp Lý",
    ft_rights: "© 2026 Wildlife Guardian. Đã đăng ký bản quyền.",
    ct_pill_1: "Đội ngũ hỗ trợ trực tuyến",
    ct_pill_2: "Phản hồi trong vòng 24 giờ",
    ct_pill_3: "Hỗ trợ 12 ngôn ngữ",
    team_chip: "👥 Đội Ngũ Của Chúng Tôi",
    team_title: "Gặp Gỡ Đội Ngũ",
    team_desc: "Những cá nhân đam mê hợp nhất bởi một sứ mệnh — bảo vệ động vật hoang dã chia sẻ hành tinh của chúng ta.",
    team_role_1: "Trưởng nhóm Phát triển & Quản lý Dự án",
    team_bio_1: "Kiến trúc nền tảng Wildlife Guardian và dẫn dắt sứ mệnh từ tầm nhìn thành hiện thực.",
    team_role_2: "Thiết kế UI/UX & Lập trình Frontend",
    team_bio_2: "Tạo ra những trải nghiệm trực quan, đẹp mắt giúp bảo tồn trở nên truyền cảm hứng và dễ tiếp cận.",
    team_role_3: "Kỹ sư Backend & Phân tích Dữ liệu",
    team_bio_3: "Xây dựng hệ thống mạnh mẽ để cung cấp năng lượng cho các hoạt động cứu hộ thời gian thực và theo dõi động vật hoang dã trên toàn cầu.",
    team_role_4: "Nhà nghiên cứu Bảo tồn",
    team_bio_4: "Tiến hành nghiên cứu thực địa để ghi chép các loài nguy cấp và cung cấp thông tin cho các chiến lược bảo tồn của nền tảng.",
    ci_chip: "✉️ Liên Hệ",
    ci_title: "Thông Tin Liên Hệ & Biểu Mẫu",
    ci_desc: "Điền vào biểu mẫu hoặc liên hệ trực tiếp với chúng tôi thông qua bất kỳ kênh nào bên dưới.",
    ci_channels: "Các Kênh Trực Tiếp",
    ci_email: "Địa Chỉ Email",
    ci_hotline: "Đường Dây Nóng Hỗ Trợ",
    ci_hq: "Trụ Sở Chính",
    ci_hours: "Giờ Làm Việc",
    ci_hours_val: "Thứ Hai – Thứ Sáu: 8:00 Sáng – 6:00 Chiều (ICT, UTC+7)",
    ci_follow: "Theo Dõi Sứ Mệnh",
    form_title: "Gửi Tin Nhắn",
    form_name: "Tên Của Bạn",
    form_name_ph: "Nguyễn Văn A",
    form_email: "Địa Chỉ Email",
    form_subject: "Chủ Đề",
    form_subject_ph: "Chúng tôi có thể giúp gì cho bạn?",
    form_msg: "Tin Nhắn Của Bạn",
    form_msg_ph: "Kể cho chúng tôi về một loài động vật đang gặp khó khăn, chia sẻ ý tưởng của bạn, hoặc chỉ đơn giản là gửi lời chào…",
    form_send: "Gửi Tin Nhắn",
    form_succ_title: "Đã gửi tin nhắn!",
    form_succ_desc: "Cảm ơn bạn đã liên hệ. Chúng tôi sẽ phản hồi lại trong vòng 24 giờ.",
    donate_badge: "❤️ Ủng Hộ Sứ Mệnh",
    donate_title: "Mỗi Khoản Quyên Góp Đều Cứu Sống Mạng Người",
    donate_desc: "Đóng góp của bạn tài trợ trực tiếp cho các hoạt động cứu hộ, phục hồi môi trường sống và công nghệ kết nối các người bảo vệ trên toàn thế giới. Không có khoản tiền nào là quá nhỏ — mỗi đồng rupee, đồng, đô la đều có giá trị.",
    donate_10: "Nuôi một con vật được cứu hộ trong một tuần",
    donate_50: "Tài trợ một ngày khảo sát thực địa",
    donate_200: "Tài trợ cho một hoạt động cứu hộ",
    donate_btn: "Quyên Góp Ngay",
    donate_learn: "Tìm Hiểu Cách Quản Lý",
    donate_trust: "🔒 Thanh toán an toàn · 100% dành cho bảo tồn · Được khấu trừ thuế ở hầu hết các quốc gia",
    btn_settings: "Cài đặt",
    btn_logout: "Đăng xuất",
    update_profile_title: "Cập nhật hồ sơ",
    update_profile_desc: "Chọn ảnh đại diện và tên hiển thị để bắt đầu!",
    name_placeholder: "Tên hiển thị của bạn...",
    btn_save_profile: "Lưu Hồ Sơ",
    btn_skip: "Bỏ qua (Ẩn danh)",
    sp_habitat: "Môi trường sống",
    sp_foundin: "Phân bố",
    sp_diet: "Chế độ ăn",
    sp_behavior: "Tập tính",
    sp_funfact: "Sự thật thú vị",
    rm_search_ph: "Tìm động vật, địa điểm...",
    rm_tab_all: "Tất cả",
    rm_tab_emergency: "Khẩn cấp",
    rm_tab_progress: "Đang xử lý",
    rm_tab_rescued: "Đã cứu",
    rm_leg_emergency: "Khẩn cấp",
    rm_leg_progress: "Đang xử lý",
    rm_leg_rescued: "Đã cứu",
    rm_fa_title: "Cẩm nang sơ cứu nhanh",
    rm_fa_1_title: "1. Giữ khoảng cách an toàn",
    rm_fa_1_desc: "Đừng vội tiếp cận. Động vật hoang dã khi hoảng sợ có thể tấn công. Hãy quan sát từ xa.",
    rm_fa_2_title: "2. Chuẩn bị hộp tối",
    rm_fa_2_desc: "Dùng hộp các-tông có lỗ thoáng khí. Lót vải mềm bên trong để tạo không gian tối và yên tĩnh.",
    rm_fa_3_title: "3. KHÔNG tự ý cho ăn",
    rm_fa_3_desc: "Cho ăn sai cách hoặc ép uống nước có thể làm con vật sặc hoặc tử vong ngay lập tức.",
    rm_fa_4_title: "4. Gọi chuyên gia",
    rm_fa_4_desc1: "Liên hệ ngay đường dây nóng ",
    rm_fa_4_desc2: " hoặc trạm cứu hộ gần nhất để được hỗ trợ.",
    rm_btn_env: "Tìm hiểu thêm tại ENV",
    rm_modal_title: "Báo cáo Động vật Cần Cứu hộ",
    rm_scan_label: "Hướng camera vào động vật",
    rm_btn_capture: " Chụp ảnh",
    rm_btn_retake: " Chụp lại",
    rm_reporter_label: "Người đăng báo cáo",
    rm_reporter_guest: "Khách",
    rm_lbl_animal: "Tên / Loài động vật *",
    rm_lbl_status: "Tình trạng *",
    rm_opt_emergency: "🚨 Khẩn cấp – Cần hỗ trợ ngay",
    rm_opt_progress: "⏳ Đang xử lý – Đã có người giúp",
    rm_opt_rescued: "✅ Đã cứu – An toàn",
    rm_lbl_phone: "SĐT Liên hệ *",
    rm_lbl_desc: "Mô tả thêm (tuỳ chọn)",
    rm_loc_loading: "Đang xác định vị trí GPS...",
    rm_loc_fetching: "Đang lấy địa chỉ...",
    rm_btn_submit: "Gửi báo cáo cứu hộ",
    rm_card_reporter: "Người báo cáo: ",
    rm_card_phone: "SĐT: ",
    rm_card_status: "Tình trạng: ",
    rm_card_desc: "Mô tả: ",
    rm_card_time: "Thời gian: ",
    rm_card_btn_guide: "Hướng dẫn sơ cứu",
    rm_card_btn_call: "Gọi chuyên gia",
    rm_status_text_emergency: "KHẨN CẤP",
    rm_status_text_progress: "ĐANG XỬ LÝ",
    rm_status_text_rescued: "ĐÃ CỨU"
  },
};
window.translations = translations;

let currentLang = localStorage.getItem("appLang") || "EN";
window.currentLang = currentLang;

function applyLanguage() {
  const t = translations[currentLang];
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const key = el.getAttribute("data-i18n");
    if (t[key]) {
      if (el.tagName === "INPUT" || el.tagName === "TEXTAREA") {
        el.setAttribute("placeholder", t[key]);
      } else {
        if (el.children.length === 0) {
          el.textContent = t[key];
        } else {
          for (let node of el.childNodes) {
            if (node.nodeType === 3 && node.nodeValue.trim().length > 0) {
              node.nodeValue = t[key];
              break;
            }
          }
        }
      }
    }
  });

  if (typeof loadPosts === "function") {
    const activeBtn = document.querySelector(".filter-btn.active");
    if (activeBtn) {
        loadPosts(activeBtn.getAttribute("data-category") || "all posts");
    }
  }

  if (typeof loadFriendRequests === "function") loadFriendRequests();
  if (typeof loadUsersForChat === "function") {
    const searchEl = document.getElementById("searchUser");
    loadUsersForChat(searchEl ? searchEl.value : "");
  }
}

document.addEventListener("DOMContentLoaded", () => {
  const langToggleBtns = document.querySelectorAll(".lang-toggle-btn");
  const langTexts = document.querySelectorAll(".lang-text");

  // Nạp ngôn ngữ vào lúc mới khởi động trang
  langTexts.forEach((span) => (span.innerText = currentLang));
  applyLanguage();

  langToggleBtns.forEach((btn) => {
    btn.addEventListener("click", () => {
      currentLang = currentLang === "EN" ? "VI" : "EN";
      window.currentLang = currentLang;
      localStorage.setItem("appLang", currentLang); // Lưu vào bộ nhớ máy để dùng cho tính năng đa ngôn ngữ
      langTexts.forEach((span) => (span.innerText = currentLang));
      applyLanguage();

      langToggleBtns.forEach((b) => {
        let currentRotation = parseInt(b.getAttribute("data-rotation") || "0");
        let newRotation = currentRotation + 180; // Xoay thêm nửa vòng 180 độ
        b.style.transform = `rotate(${newRotation}deg)`;
        b.setAttribute("data-rotation", newRotation);
      });
    });
  });
});
